version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/authentication"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/inventory"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/payment"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/notification"
    schedule:
      interval: "weekly"
