sonar:
  projectKey: green-cart
  projectName: Green-Cart
  projectVersion: 1.0.0

projectBaseDir: .

tests:
  inclusions:
    - '**/*.test.ts'
    - '**/*.test.tsx'
  exclusions:
    - 'node_modules/**'
    - '**/node_modules/**'
    - 'coverage/**'

coverage:
  exclusions:
    - '**/*.test.ts'
    - '**/*.test.tsx'
    - '**/node_modules/**'
    - 'coverage/**'
    - '.next/**'
    - 'dist/**'
    - 'build/**'

qualityGate:
  waitForQualityGate: false
  skipGateCheck: true

languageAnalysis:
  skipLinterWarnings: true
  skipSonarSecurityRules: false
