name: Authentication CI

on:
  push:
    paths:
      - "authentication/**"
      - ".github/workflows/authentication-ci.yml"
  pull_request:
    paths:
      - "authentication/**"
      - ".github/workflows/authentication-ci.yml"

permissions:
  contents: read

jobs:
  service-ci:
    name: authentication - Service CI
    uses: ./.github/workflows/_service-ci-template.yml
    with:
      service_name: authentication
    secrets: inherit
