name: Notification CI

on:
  push:
    paths:
      - "notification/**"
      - ".github/workflows/notification-ci.yml"
  pull_request:
    paths:
      - "notification/**"
      - ".github/workflows/notification-ci.yml"

permissions:
  contents: read

jobs:
  service-ci:
    name: notification - Service CI
    uses: ./.github/workflows/_service-ci-template.yml
    with:
      service_name: notification
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
