name: Payment CI

on:
  workflow_dispatch:
  push:
    paths:
      - "payment/**"
      - ".github/workflows/payment-ci.yml"
      - ".github/workflows/_service-ci-template.yml"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "payment/**"
      - ".github/workflows/payment-ci.yml"
      - ".github/workflows/_service-ci-template.yml"

permissions:
  contents: read
  pull-requests: read

jobs:
  service-ci:
    name: payment - Service CI
    uses: ./.github/workflows/_service-ci-template.yml
    with:
      service_name: payment
